apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: gardener-extension-validator-openstack
webhooks:
- name: validation.openstack.provider.extensions.gardener.cloud
  rules:
  - apiGroups:
    - "core.gardener.cloud"
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shoots
  failurePolicy: Fail
  objectSelector: {}
  namespaceSelector: {}
  sideEffects: None
  clientConfig:
    url: "https://localhost:9443/webhooks/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMxRENDQWJ3Q0NRRDBmWGtUcmptU1dqQU5CZ2txaGtpRzl3MEJBUXNGQURBc01SRXdEd1lEVlFRS0RBaEgKWVhKa1pXNWxjakVYTUJVR0ExVUVBd3dPWjJGeVpHVnVaWEl1WTJ4dmRXUXdIaGNOTWpBd016QTBNVFUxTmpJeApXaGNOTXpBd016QXlNVFUxTmpJeFdqQXNNUkV3RHdZRFZRUUtEQWhIWVhKa1pXNWxjakVYTUJVR0ExVUVBd3dPCloyRnlaR1Z1WlhJdVkyeHZkV1F3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRHMKYytWMHVXSjNqSTZNRDBKVkY3eEcyYzFleEU4RzdZd3NBWmNLQUlnM0JnN2x2eG4vcnlrSlN3RkI4cHAxR3lDegpuMTM5Y2lubnFRN3RGRkpZRkVKb2tNeUNIUHliM0t2MFRZODBjY0lIN3Y0WSsrVSsxaDg5MWVTOXh1b0hiZjN3CnFMUUdFb3NnNmJSZ0ZZWHZUZTFQQWw2SGRVWmtmMkhjeUoxY0FCdUNOaXRxTCtqZDRMOUpXR3ozQ3VhSUpsYkgKQnA2czFYeGIxZTFmMzhIbi84YjkvdVJhUVZLRTJHbTlTck5vSDg5L0I2NHU4ZFdhT1RHT09lNk00Vng2eXdHdgp0ZDBLaDNxdTRwMW9sem43a25EZ0I1UG1ES3o1RWVzR1pKOHNaejQydFozNzI3YjhDekNBV25FTEtITFZJbmJ4CmlFaEJnYmp5bVZ2ODZ1SmFjWnBsQWdNQkFBRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQjA5VitxOGFqdFgKZEZsekEvMWY0YjQveVNVOVF3Q2FzSnRjdnFWaUJoMWRnWnY3YVhCSjN3MkpoVVJLUS90UDZvaUpUOTErdmpwSQpYRmtFTjY3VVhGdlBxNVR4Um1SNkYvTzNJK2pkZXRFNjVFdy9CUnlXTkc3bjFmSUNGd3BkUmNibU9INXNIUldXCkFxbFBmaENzTTI1RjBTc2tiTU1XNUM0QzlEeDNNQVcydWpoWk5GVTBBUTh4ODI5RFFmYkQ1TUZvZFhSejJieGgKV0x1TXJZak5PNi95THV5b1EyNFJ2MVNoNTdBYml5My9nYUN1TEQ4RTJTL255VktNM1c4UTg1L2FTKytzd3FVNwpDOUJUaWIrRmFRZU54YXY0QUV6TnpTNHRMdHEvS3ozTUJvUWl6ZDRQR3FSMmZkTUt3UDYza3ZjY3pBL1FRakdsClhoczI5YnlGQVFJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
