{{- if not .Values.useLegacyProvisioner }}
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: cinder.csi.openstack.org
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: cinder.csi.openstack.org
{{- end }}
