{{- if .Values.useLegacyProvisioner }}
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    resources.gardener.cloud/delete-on-invalid-update: "true"
allowVolumeExpansion: true
provisioner: kubernetes.io/cinder
{{- if semverCompare ">= 1.12-0" .Capabilities.KubeVersion.GitVersion }}
volumeBindingMode: WaitForFirstConsumer
{{- else }}
volumeBindingMode: Immediate
{{- end }}
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    resources.gardener.cloud/delete-on-invalid-update: "true"
allowVolumeExpansion: true
provisioner: kubernetes.io/cinder
{{- if semverCompare ">= 1.12-0" .Capabilities.KubeVersion.GitVersion }}
volumeBindingMode: WaitForFirstConsumer
{{- else }}
volumeBindingMode: Immediate
{{- end }}
{{- end }}
