apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
{{ include "labels" . | indent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret-gardener-extension-validator-openstack-cert: {{ include (print $.Template.BasePath "/secret-cert.yaml") . | sha256sum }}
        {{- if .Values.global.kubeconfig }}
        checksum/gardener-extension-validator-openstack-kubeconfig: {{ include (print $.Template.BasePath "/secret-kubeconfig.yaml") . | sha256sum }}
        {{- end }}
      labels:
{{ include "labels" . | indent 8 }}
    spec:
      {{- if .Values.global.kubeconfig }}
      automountServiceAccountToken: false
      {{- else }}
      serviceAccountName: {{ include "name" . }}
      {{- end }}
      containers:
      - name: {{ include "name" . }}
        image: {{ include "image" .Values.global.image }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
        - /gardener-extension-validator-openstack
        - --webhook-config-server-port={{ .Values.global.webhookConfig.serverPort }}
        - --webhook-config-cert-dir=/etc/gardener-extension-validator-openstack/srv
        {{- if .Values.global.kubeconfig }}
        - --kubeconfig=/etc/gardener-extension-validator-openstack/kubeconfig/kubeconfig
        {{- end }}
        ports:
        - name: webhook-server
          containerPort: {{ .Values.global.webhookConfig.serverPort }}
          protocol: TCP
{{- if .Values.global.resources }}
        resources:
{{ toYaml .Values.global.resources | nindent 10 }}
{{- end }}
        volumeMounts:
        - name: gardener-extension-validator-openstack-cert
          mountPath: /etc/gardener-extension-validator-openstack/srv
          readOnly: true
        {{- if .Values.global.kubeconfig }}
        - name: gardener-extension-validator-openstack-kubeconfig
          mountPath: /etc/gardener-extension-validator-openstack/kubeconfig
          readOnly: true
        {{- end }}
      volumes:
      - name: gardener-extension-validator-openstack-cert
        secret:
          secretName: gardener-extension-validator-openstack-cert
          defaultMode: 420
      {{- if .Values.global.kubeconfig }}
      - name: gardener-extension-validator-openstack-kubeconfig
        secret:
          secretName: gardener-extension-validator-openstack-kubeconfig
          defaultMode: 420
      {{- end }}
